### PR TITLE
Simple ICommand implementation and upgraded to .net 4.5

### PR DESCRIPTION
**Pull request by MihaMarkic**
Here is a working simple ICommand implementation, good enough for MVVM. No CommandManager support at this time nor CommandTarget support.
I also upgraded non-Web projects to .net 4.5 (since ICommand moved to System assembly).
Also added [Moq](https://code.google.com/p/moq/) package to unit tests.

### CODE REVIEW

**Comment by yuvaltz** [comment]
Looks great
I think it would be better to have the .net upgrade changes in a separate commit

**Comment by MihaMarkic** [comment]
Probably, but the two are connected anyways.

**Comment by yuvaltz** [comment]
ok, I'll change it a bit and merge it in a few hours

**Comment by yuvaltz** [comment]
The new test file should be added as a link to Granular.Presentation.Tests.Web, but it won't compile since we don't have a "Saltarelle" version of Moq.
If you want, you can copy the sources of Moq you are using to Granular.UnitTesting.Web, so we'll have it in the web test too.

**Comment by MihaMarkic** [comment]
Of course, I realized that the moment I hit "Comment" button :)
Removed Moq, now it should run and compile fine.

**Pull request closed without merging**
